# Generated by Django 4.2.7 on 2026-09-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Briefly describe what this resource contains.')),
                ('subject', models.CharField(help_text='e.g., Data Structures, Operating Systems', max_length=100)),
                ('semester', models.PositiveIntegerField(help_text='e.g., 1 to 8')),
                ('resource_type', models.CharField(choices=[('Notes', 'Notes'), ('Study Material', 'Study Material'), ('Previous Year Question Paper', 'Previous Year Question Paper'), ('Lab Manual', 'Lab Manual'), ('Assignment', 'Assignment'), ('Reference Material', 'Reference Material'), ('Useful Link', 'Useful Link'), ('Other', 'Other')], default='Notes', max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated keywords, e.g., python, algorithms, mid-term', max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('external_url', models.URLField(blank=True, help_text='Link to Google Drive, GitHub, etc.', null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
