# Generated by Django 4.2.7 on 2026-09-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
