# Generated by Django 4.2.7 on 2026-09-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('AIE', 'AI & ML'), ('ECE', 'Electronics & Comm'), ('CCE', 'Computer & Comm'), ('CSQC', 'CS & Quantum Computing'), ('AIDS', 'AI & Data Science'), ('EEE', 'Electrical & Electronics'), ('ME', 'Mechanical'), ('CIVIL', 'Civil Engineering')], default='CSE', max_length=10),
        ),
    ]
