# Generated by Django 4.2.7 on 2026-09-26 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resource_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('AIE', 'AI & ML'), ('ECE', 'Electronics & Comm'), ('CCE', 'Computer & Comm'), ('CSQC', 'CS & Quantum Computing'), ('AIDS', 'AI & Data Science'), ('EEE', 'Electrical & Electronics'), ('ME', 'Mechanical'), ('CIVIL', 'Civil Engineering')], max_length=10),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='resources.resource')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
