# Generated by Django 4.2.7 on 2026-09-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_resource_branch_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
